### ISSUE TITLE
json.loadsでエラーが出ました

### ISSUE THREAD

**Issue by karaage0703** [hokekiyoo/taikutsu_blog_works#5]
面白そうなので試してみたのですが、エラーが出てしまいました。
```
python all_in_one.py -u http://karaage.hatenadiary.jp -d karaage -g -i -b -l
1/1697 2017-12-25-073000
Traceback (most recent call last):
  File "all_in_one.py", line 295, in <module>
    main()
  File "all_in_one.py", line 262, in main
    info = json.loads(data.strip('(').rstrip(')'), "r")
TypeError: loads() takes 1 positional argument but 2 were given
```

　ちょっと自分ではパッと直しかた分かりませんでした、もし分かりましたら教えて下さい（特に急いでいたりするわけではないです）。

　Macのpyenv環境でanaconda入れて試しています。バージョンは以下です。
```
python 3.6.1
beautifulsoup4 4.6.0
matplotlib 2.0.2
networkx 1.11
numpy 1.12.1
```

**Comment by karaage0703** [comment]
問題ですが、自己解決しましたー。エラーメッセージに従って勘でオプション減らしてみたら動きました（笑）

```
-    info = json.loads(data.strip('(').rstrip(')'), "r")
+    info = json.loads(data.strip('(').rstrip(')'))
```

そちらで動くのはバージョンの違いでしょうか？関係するバージョンって `jsonschema==2.6.0` とかになるのでしょうかね…？jsonは全然詳しくないです…
